version: '1'
services:
  app1:
    build: ./app1
    ports:
      - "4000:4000"
    networks:
      - unidad3

  app2:
    build: ./app2
    ports:
      - "4001:4001"
    depends_on:
      - app1
    networks:
      - unidad3

networks:
  unidad3:
    external: false